# Generated by Django 5.2.4 on 2025-08-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_user_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
