# Generated by Django 5.2.3 on 2025-07-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Trader', 'trader'), ('recycler', 'Recycler')], max_length=50),
        ),
    ]
