
# Generated by Django 5.2.4 on 2025-07-13 09:30

import django.utils.timezone

# Generated by Django 5.2.4 on 2025-07-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',

            field=models.CharField(choices=[('Trader', 'trader'), ('recycler', 'Recycler')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,

            field=models.CharField(choices=[('Trader', 'trader'), ('recycler', 'Recycler')], default='Trader', max_length=50),

        ),
    ]
