# Generated by Django 5.2.3 on 2025-07-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Trader', 'trader'), ('recycler', 'Recycler')], max_length=50, null=True),
        ),
    ]
