# Generated by Django 5.2.4 on 2025-08-05 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points_award', models.CharField(max_length=10)),
                ('payment_method', models.CharField(default='M-Pesa', max_length=30)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], max_length=30)),
                ('phone_number', models.IntegerField()),
                ('mpesa_receipt_number', models.CharField(max_length=100)),
                ('paid_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
