# Generated by Django 5.2.3 on 2025-07-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
