# Generated by Django 5.2.3 on 2025-06-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(max_length=500)),
            ],
        ),
    ]
