# Generated by Django 5.2.3 on 2025-07-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('users', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
