# Generated by Django 5.2.4 on 2025-07-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_at',
            new_name='created_at',
        ),
    ]
