# Generated by Django 5.2.4 on 2025-07-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_feedback_at_feedback_created_at'),
        ('users', '0001_initial'),
    ]
    



    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_type',
            field=models.CharField(default='Trader', max_length=50),
        ),
    ]
