# Generated by Django 5.2.3 on 2025-06-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('reward_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('rewards', models.CharField(max_length=100)),
                ('rewards_at', models.DateTimeField()),
            ],
        ),
    ]
