# Generated by Django 5.2.3 on 2025-07-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
