# Generated by Django 5.2.3 on 2025-07-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_alter_reward_reward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
