# Generated by Django 5.2.3 on 2025-06-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('trader_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], max_length=50)),
                ('pickup_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
