# Generated by Django 5.2.3 on 2025-07-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('pickup', '0001_initial'),
        ('users', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup',
            old_name='latitude',
            new_name='market_latitude',
        ),
        migrations.RenameField(
            model_name='pickup',
            old_name='longitude',
            new_name='market_longitude',
        ),
        migrations.RemoveField(
            model_name='pickup',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='pickup',
            name='trader_name',
        ),
        migrations.AddField(
            model_name='pickup',
            name='market_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pickup',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material'),
        ),
        migrations.AddField(
            model_name='pickup',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
