# Generated by Django 5.2.4 on 2025-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('reward_id', models.AutoField(primary_key=True, serialize=False)),
                ('rewards', models.CharField(max_length=100)),
                ('rewards_at', models.DateTimeField()),
            ],
        ),
    ]
