# Generated by Django 5.2.4 on 2025-07-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_name', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('listed_at', models.DateTimeField()),
            ],
        ),
    ]
