"""
Django settings for Ecorise project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(=&vvaohu)4_g$zeh3c(t_(9f4rswh#3=ga-iy#+-jp=7r8h+d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'pickup',
    

    'users',


    'product',
    'material',
   
    'api',



    



    'feedback',
    'payment',
   
    'rest_framework',
    

    'reward',
   
  

    

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ecorise.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ecorise.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DARAJA_CONSUMER_KEY = 'YhLSHyufTdMqlIGGe2zUp7GzeYR59e54C4R76coccI83zxZd'
DARAJA_CONSUMER_SECRET = 'lYno0p1k7dFNsfJJfAlR2ILbFQtAH7XkWpdpV67qdlU4FNuzpUxyxuL9KKasXPYr'
DARAJA_INITIATOR_NAME = 'testapi'
DARAJA_SHORTCODE = '600986'
DARAJA_SECURITY_CREDENTIAL = 'KKx0nj7ydMetiHSIdUEqlN0sAv1LxBBArMtjaHVZXIvmUK5jm75YhAUVNtEH0opLQY172qVK+an9O+CInMtAETR/I8zoLwyVcmXyXK65EHw7KBgOXSrv38lMVMouovr78Soli+3Tsz0INwFMl+RPVDoe2a/tFye3c7Gqa3sNVRC7ZhDH9L0nbRMWrAxquy169uAcNN5yEK/8qRQO3VzWwNA9QYAXinxNIibpJrQoD0uGLS+CIWuzLPSU4Xwk/YlyqJus9WLufZTt2zVl8vzaLexFLCun8EtBIbDNtTFu0wOV18bS9Q99rbNrd9iAfHStOHA9Ltve85hC2wicIB+1Sg=='
DARAJA_B2C_RESULT_URL = 'https://1234abcd.ngrok.io/api/payments/daraja-callback/'
DARAJA_B2C_QUEUE_TIMEOUT_URL = 'https://1234abcd.ngrok.io/api/payments/daraja-callback/'
LOGGING = {
   'version': 1,
   'disable_existing_loggers': False,
   'handlers': {
       'console': {
           'class': 'logging.StreamHandler',
       },
   },
   'loggers': {
       '': {
           'handlers': ['console'],
           'level': 'DEBUG',
           'propagate': True,
       },
   },
}